Page({
    data:{
      res:[]
    },
    onLoad(options){
        wx.cloud.callFunction({
            name:"getdatabyid",
            data:{
                dbname:'activeList',
                id:options.id
            }
          }).then(res=>{
            console.log(res)
            this.setData({
              res:res.result.data
            })
          })
    }
  })